---
- hosts: all
  gather_facts: False
  name: Spin up and configure testing environment in DigitalOcean
  tasks:
    - name: Spin up DigitalOcean droplets
      digital_ocean:
        api_token: '{{ digital_ocean_api_token }}'
        command: droplet
        name: '{{ inventory_hostname }}'
        unique_name: yes
        image_id: '{{ digital_ocean_image }}'
        region_id: '{{ digital_ocean_region }}'
        size_id: '{{ digital_ocean_size }}'
        ssh_key_ids: '{{ digital_ocean_ssh_keys }}'
        state: present
      delegate_to: localhost
