- hosts: all
  name: Run various tests with zabbix_host and zabbix_host_facts modules
  tasks:
    - block:
        - name: Create hostgroup in Zabbix (new)
          zabbix_group:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            host_groups: '{{ zbx_test_group_name }}'
            state: present

        - name: Create host in Zabbix (new)
          zabbix_host:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            host_name: '{{ inventory_hostname }}'
            host_groups: '{{ zbx_test_group_name }}'
            link_templates: '{{ zbx_icmp_template }}'
            status: enabled
            state: present
            interfaces:
              - type: 1
                main: 1
                useip: 1
                ip: '{{ ansible_default_ipv4.address }}'
          register: _host_new

        - assert:
            that: _host_new.changed

        - name: Create host in Zabbix (existing)
          zabbix_host:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            host_name: '{{ inventory_hostname }}'
            host_groups: '{{ zbx_test_group_name }}'
            link_templates: '{{ zbx_icmp_template }}'
            status: enabled
            state: present
            interfaces:
              - type: 1
                main: 1
                useip: 1
                ip: '{{ ansible_default_ipv4.address }}'
          register: _host_existing

        - assert:
            that: not _host_existing.changed

        - name: Retreive facts about newly created host
          zabbix_host_facts:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            host_name: '{{ inventory_hostname }}'
          register: _host_facts

        - assert:
            that:
              - _host_facts.hosts[0].host == inventory_hostname
              - _host_facts.hosts[0].hostid|int > 0

        - name: Delete host in Zabbix (existing)
          zabbix_host:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            host_name: '{{ inventory_hostname }}'
            state: absent
          register: _host_existing_del
          tags:
            - cleanup

        - assert:
            that: _host_existing_del.changed

        - name: Delete host in Zabbix (missing)
          zabbix_host:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            host_name: '{{ inventory_hostname }}'
            state: absent
          register: _host_missing_del

        - assert:
            that: not _host_missing_del.changed

      delegate_to: localhost
