- hosts: all
  name: Run tests with zabbix_user module
  tasks:
    - block:
        - name: Create Zabbix user (new)
          zabbix_user:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            alias: example
            name: user name
            surname: user surname
            usrgrps:
              - Guests
              - Disabled
            passwd: password
            lang: en_GB
            theme: blue-theme
            autologin: no
            autologout: 0
            refresh: 30
            rows_per_page: 200
            after_login_url: ''
            user_medias:
              - mediatype: Email
                sendto: example@example.com
                period: 1-7,00:00-24:00
                severity:
                  not_classified: no
                  infomation: yes
                  warning: yes
                  average: yes
                  high: yes
                  disaster: yes
                active: no
            type: Zabbix super admin
            state: present
          register: zbx_user_new

        - debug:
            msg: '{{ zbx_user_new }}'

        - assert:
            that: zbx_user_new.changed

        - name: Create Zabbix user (existing)
          zabbix_user:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            alias: example
            name: user name
            surname: user surname
            usrgrps:
              - Guests
              - Disabled
            passwd: password
            lang: en_GB
            theme: blue-theme
            autologin: no
            autologout: 0
            refresh: 30
            rows_per_page: 200
            after_login_url: ''
            user_medias:
              - mediatype: Email
                sendto: example@example.com
                period: 1-7,00:00-24:00
                severity:
                  not_classified: no
                  infomation: yes
                  warning: yes
                  average: yes
                  high: yes
                  disaster: yes
                active: no
            type: Zabbix super admin
            state: present
          register: zbx_user_existing

        - assert:
            that: not zbx_user_existing.changed

      delegate_to: localhost
