- hosts: all
  name: Run various tests with zabbix_host and zabbix_hostmacro modules
  vars:
    zbx_host_macros:
      - key: LOW_SPACE_LIMIT:/home
        value: 10

  tasks:
    - block:
      - name: Create host in zabbix
        zabbix_host:
          server_url: '{{ zbx_server_url }}'
          login_user: '{{ zbx_user }}'
          login_password: '{{ zbx_password }}'
          host_name: '{{ inventory_hostname }}'
          visible_name: '{{ inventory_hostname }}'
          validate_certs: '{{ zbx_validate_certs }}'
          force: no
          host_groups:
            - Linux servers
          link_templates:
            - '{{ zbx_icmp_template }}'
          status: enabled
          state: present
          inventory_mode: disabled
          interfaces:
            - type: 1
              main: 1
              useip: 0
              ip: "{{ ansible_default_ipv4.address }}"
              dns: "{{ inventory_hostname }}"
              port: 10050

      - name: Create host macros (new)
        zabbix_hostmacro:
          server_url: '{{ zbx_server_url }}'
          login_user: '{{ zbx_user }}'
          login_password: '{{ zbx_password }}'
          validate_certs: '{{ zbx_validate_certs }}'
          host_name: '{{ inventory_hostname }}'
          macro_name: '{{ item.key }}'
          macro_value: '{{ item.value }}'
          state: present
        loop: '{{ zbx_host_macros }}'
        register: _macros_new

      - assert:
          that:
            - _macros_new.changed

      - name: Create host macros (existing)
        zabbix_hostmacro:
          server_url: '{{ zbx_server_url }}'
          login_user: '{{ zbx_user }}'
          login_password: '{{ zbx_password }}'
          validate_certs: '{{ zbx_validate_certs }}'
          host_name: '{{ inventory_hostname }}'
          macro_name: '{{ item.key }}'
          macro_value: '{{ item.value }}'
          state: present
        loop: '{{ zbx_host_macros }}'
        register: _macros_new

      - assert:
          that:
            - not _macros_new.changed

      delegate_to: localhost
