- hosts: all
  tasks:
    - block:
        - name: Create template 00_temp1 new
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp1
            template_groups: Templates
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp1 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp1
            template_groups: Templates
            state: present
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Create template 00_temp2 new
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp2
                    name: 00_temp2
                    description: '2nd testing template'
                    templates:
                      - name: '{{ zbx_icmp_template }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '1234'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '3.0'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp2 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp2
                    name: 00_temp2
                    description: '2nd testing template'
                    templates:
                      - name: '{{ zbx_icmp_template }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '1234'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '3.0'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Create template 00_temp2 changed
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp2
                    name: 00_temp2
                    description: '2nd testing template'
                    templates:
                      - name: '{{ zbx_icmp_template }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '12345'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '3.0'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp3 new
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp3
            template_groups: Templates
            link_templates:
              - '{{ zbx_icmp_template }}'
            macros:
              - macro: '{$TEST}'
                value: '123'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp3 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp3
            template_groups: Templates
            link_templates:
              - '{{ zbx_icmp_template }}'
            macros:
              - macro: '{$TEST}'
                value: '123'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Create template 00_temp4 new
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp4
                    name: 00_temp4
                    description: '4th testing template'
                    templates:
                      - name: '{{ zbx_icmp_template }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '12345'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '3.0'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp4 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json:
              zabbix_export:
                templates:
                  - template: 00_temp4
                    name: 00_temp4
                    description: '4th testing template'
                    templates:
                      - name: '{{ zbx_icmp_template }}'
                    groups:
                      - name: 'Templates'
                    macros:
                      - macro: '{$TEST}'
                        value: '12345'
                      - macro: '{$TEST2}'
                        value: 'mystr'
                version: '3.0'
            state: present
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Dump template JSON
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp3
            state: dump

        - name: Dump templates XML
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp3
            dump_format: xml
            state: dump

        - name: Create template 00_temp5 fail
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp5
            state: present
          register: res
          ignore_errors: True

        - assert:
            that:
              - "res.failed == True"

        - name: Create template 00_temp6 from JSON file (new)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json: "{{ lookup('file', 'files/00_temp6.json') }}"
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp6 from JSON file (existing)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json: "{{ lookup('file', 'files/00_temp6.json') }}"
            state: present
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Create template 00_temp6 from JSON file (altered)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_json: "{{ lookup('file', 'files/00_temp6_altered.json') }}"
            state: present
          register: res

        - assert:
            that:
              - "res.changed == True"

        - name: Create template 00_temp7 from XML file (new)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_xml: "{{ lookup('file', 'files/00_temp7.xml' ) }}"
            state: present
          register: res
          tags:
            - xml_support

        - assert:
            that:
              - "res.changed == True"
          tags:
            - xml_support

        - name: Create template 00_temp7 from XML file (existing)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_xml: "{{ lookup('file', 'files/00_temp7.xml' ) }}"
            state: present
          register: res
          tags:
            - xml_support

        - assert:
            that:
              - "res.changed == False"
          tags:
            - xml_support

        - name: Create template 00_temp7 from XML file (altered)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_xml: "{{ lookup('file', 'files/00_temp7_altered.xml' ) }}"
            state: present
          register: res
          tags:
            - xml_support

        - assert:
            that:
              - "res.changed == True"
          tags:
            - xml_support

        - name: Test creation of multiple templates at once
          block:
            - name: Create multiple templates from JSON (new)
              zabbix_template:
                server_url: '{{ zbx_server_url }}'
                login_user: '{{ zbx_user }}'
                login_password: '{{ zbx_password }}'
                validate_certs: '{{ zbx_validate_certs }}'
                template_json: "{{ lookup('file', 'files/multiple_templates.json' ) }}"
                state: present
              register: res

            - assert:
                that:
                  - "res.changed == True"

            - name: Create multiple templates from JSON (existing)
              zabbix_template:
                server_url: '{{ zbx_server_url }}'
                login_user: '{{ zbx_user }}'
                login_password: '{{ zbx_password }}'
                validate_certs: '{{ zbx_validate_certs }}'
                template_json: "{{ lookup('file', 'files/multiple_templates.json' ) }}"
                state: present
              register: res

            - assert:
                that:
                  - "res.changed == False"

            - name: Remove those templates
              zabbix_template:
                server_url: '{{ zbx_server_url }}'
                login_user: '{{ zbx_user }}'
                login_password: '{{ zbx_password }}'
                validate_certs: '{{ zbx_validate_certs }}'
                template_name: '{{ item }}'
                state: absent
              loop:
                - 00_temp8
                - 00_temp9
                - 00_temp10

            - name: Create multiple templates from XML (new)
              zabbix_template:
                server_url: '{{ zbx_server_url }}'
                login_user: '{{ zbx_user }}'
                login_password: '{{ zbx_password }}'
                validate_certs: '{{ zbx_validate_certs }}'
                template_xml: "{{ lookup('file', 'files/multiple_templates.xml' ) }}"
                state: present
              register: res

            - assert:
                that:
                  - "res.changed == True"

            - name: Create multiple templates from XML (existing)
              zabbix_template:
                server_url: '{{ zbx_server_url }}'
                login_user: '{{ zbx_user }}'
                login_password: '{{ zbx_password }}'
                validate_certs: '{{ zbx_validate_certs }}'
                template_xml: "{{ lookup('file', 'files/multiple_templates.xml' ) }}"
                state: present
              register: res

            - assert:
                that:
                  - "res.changed == False"

          when: zbx_version >= 4.0

        - name: Remove template 00_temp1 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp1
            state: absent
          register: res
          tags:
            - cleanup

        - assert:
            that:
              - "res.changed == True"

        - name: Remove template 00_temp2 existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp2
            state: absent
          register: res
          tags:
            - cleanup

        - assert:
            that:
              - "res.changed == True"

        - name: Remove template 00_temp2 non existing
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: 00_temp1
            state: absent
          register: res

        - assert:
            that:
              - "res.changed == False"

        - name: Remove rest of the templates (existing)
          zabbix_template:
            server_url: '{{ zbx_server_url }}'
            login_user: '{{ zbx_user }}'
            login_password: '{{ zbx_password }}'
            validate_certs: '{{ zbx_validate_certs }}'
            template_name: '{{ item }}'
            state: absent
          loop:
            - 00_temp3
            - 00_temp4
            - 00_temp6
            - 00_temp7
            - 00_temp8
            - 00_temp9
            - 00_temp10

          register: res
          tags:
            - cleanup

        - assert:
            that:
              - "res.changed == True"

      delegate_to: localhost
